$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://seikosf25.jp/schemas/source/booth.schema.yaml"
title: "Config"
description: "schema for booth.yaml. This defines the structure for individual booth information files."
type: "object"
