# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://assets.seikosf25.jp/schemas/source/config.schema.yaml"
title: "Global Configuration Schema"
description: "アプリケーション全体のグローバル設定を定義するスキーマ。"
type: "object"